trigger:
  - master

pool: 
  vmImage: 'Windows-2019'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  Pack_BuildNumber: '1.0.$(Build.BuildID)'

steps:
# Release notes to wiki
- task: XplatGenerateReleaseNotes@2
  inputs:
    outputfile: 'Release.md'
    templateLocation: 'File'
    templatefile: 'Documentation\ReleaseNoteTemplate.md'
    delimiter: ':'
    fieldEquality: '='
